pretrain: true # true # false  # Whether to use pre-training
pretrained_model: /home/disk2/xxr/now/GPT-last-new/log/chembl/crossdocked/char/2025_05_16_00/val_model.pt # /home/zql/Code/HGNN-GPT/GPT-last-new/save/chembl/pdbbind/char/2024_12_27_19/val_model.pt # /home/zql/Code/HGNN-GPT/GPT-last-new/save/chembl/crossdocked/char/2024_12_26_20/val_model.pt #   /home/zql/Code/HGNN-GPT/GPT-last-new/save/chembl/crossdocked/char/2024_12_26_20/val_model.pt    
vocab_size: 48  # 54 # 48 # 48    char: 54, 48   selfies: 109
block_size: 121   # 121 #119
n_embd: 256
num_props: 1        # Whether to include protein pocket information 1,0
n_layer: 8          # Number of layers in GPT block
n_head: 8
embd_pdrop: 0.1    # GPT input embedded parameters
attn_pdrop: 0.1    # GPT attention weight parameters
resid_pdrop: 0.1   # Dropout parameter for GPT residuals
sample: false       
scaffold_maxlen: 0 
use_gate: true # true # true
att_num: 1   # 1or2
use_encoder_norm: false # false
use_alpha: true # true

