pretrain: true # true # false  # Whether to use pre-training
pretrained_model: 
vocab_size: 48 
block_size: 121 
n_embd: 256
num_props: 1        # Whether to include protein pocket information 1,0
n_layer: 8          # Number of layers in GPT block
n_head: 8
embd_pdrop: 0.1    # GPT input embedded parameters
attn_pdrop: 0.1    # GPT attention weight parameters
resid_pdrop: 0.1   # Dropout parameter for GPT residuals
sample: false       
scaffold_maxlen: 0 
use_gate: true # true # true
att_num: 1   # 1or2
use_encoder_norm: false # false
use_alpha: true # true

